[package]
name = "trembita-showcase-workflows"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
trembita = { path = "../../crates/trembita", features = ["http-jobs"] }
trembita-runtime = { path = "../../crates/trembita-runtime" }
trembita-showcase-common = { path = "../../crates/trembita-showcase-common" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal", "time", "net"] }
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
