[package]
name = "crafty-client"
description = "In-process and remote (HTTP/3) client API for crafty."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true

[dependencies]
crafty-proto.workspace = true
crafty-core.workspace = true
crafty-net.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
tokio = { version = "1", features = ["time"] }

[dev-dependencies]
crafty-actor.workspace = true
crafty-test-support.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "sync", "test-util"] }
