[package]
name = "trembita-sim"
description = "Deterministic simulation harness for testing trembita clusters."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
readme = "README.md"
homepage.workspace = true

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true

[dependencies]
trembita-proto.workspace = true
trembita-core.workspace = true

[dev-dependencies]
proptest = "1"
trembita-runtime.workspace = true
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
