upstream trembita_elastic {
    server node1:7443;
    server node2:7443;
    server node3:7443;
    server node4:7443;
}

server {
    listen 8080;
    location / {
        proxy_pass http://trembita_elastic;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Connection "";
    }
}
