//! I5 scenario: check that histories generated by the deterministic Raft
//! simulator, treated as a replicated single-register, are linearizable — and
//! that the checker catches a deliberately corrupted history.

use craft_sim::{Cluster, History, Model};

/// A single u64 register. `Write(v)` sets and echoes `v`; `Read` returns the
/// current value. Matches how the scenario replicates writes through Raft.
#[derive(Clone)]
enum Op {
    Write(u64),
    Read,
}

struct Register;

impl Model for Register {
    type State = u64;
    type Input = Op;
    type Output = u64;

    fn init(&self) -> u64 {
        0
    }

    fn apply(&self, state: &u64, input: &Op) -> (u64, u64) {
        match input {
            Op::Write(v) => (*v, *v),
            Op::Read => (*state, *state),
        }
    }
}

fn decode(bytes: &[u8]) -> u64 {
    let mut buf = [0u8; 8];
    buf.copy_from_slice(bytes);
    u64::from_le_bytes(buf)
}

/// Run a stable cluster as a replicated register with a write concurrent with a
/// read each round, returning the recorded history. `corrupt_read` (if set)
/// overwrites the observed value of the read in that round to force a
/// non-linearizable history.
fn run_register_history(corrupt_read: Option<u64>) -> History<Op, u64> {
    let mut cluster = Cluster::new(3, 0x1A5E_u64);
    assert!(cluster.run_until_leader(200), "cluster elected a leader");

    let mut history = History::new();
    for v in 1..=6u64 {
        let leader = cluster.leader().expect("stable leader");

        // Start a write (client 0) and a concurrent read (client 1).
        history.invoke(0, Op::Write(v));
        assert!(
            cluster.propose(v.to_le_bytes().to_vec()),
            "leader accepts write"
        );

        history.invoke(1, Op::Read);
        let read_id = 1000 + v;
        assert!(cluster.read_index(read_id), "leader accepts read");

        // Advance until both the read confirms and the write has applied.
        for _ in 0..300 {
            let applied = cluster.applied(leader).len() as u64;
            if cluster.read_ready(read_id).is_some() && applied >= v {
                break;
            }
            cluster.run(1);
        }
        assert!(
            cluster.read_ready(read_id).is_some(),
            "read {read_id} confirmed"
        );

        // The read linearizes to the register's current committed value.
        let observed = cluster
            .applied(leader)
            .last()
            .map(|c| decode(c))
            .unwrap_or(0);
        let observed = match corrupt_read {
            Some(round) if round == v => observed.wrapping_add(777), // never-written value
            _ => observed,
        };
        history.response(1, observed);
        history.response(0, v); // Write echoes v
    }
    history
}

#[test]
fn simulated_register_history_is_linearizable() {
    let history = run_register_history(None);
    assert!(
        history.is_linearizable(&Register),
        "Raft-replicated register history must be linearizable"
    );
}

#[test]
fn corrupted_read_makes_the_history_non_linearizable() {
    // Inject a bogus observed value into round 3's read.
    let history = run_register_history(Some(3));
    assert!(
        !history.is_linearizable(&Register),
        "a read returning a never-written value must be flagged"
    );
}
