//! Queue consumer helpers ([`JobConsumer`], [`ConsumerOpts`], [`CraftyApp::spawn_consumer`]).

use std::future::Future;
use std::sync::Arc;
use std::time::Duration;

use crafty_actor::{WorkerId, run_queue_consumer};

use crate::CraftyApp;

type ConsumerSpawnFn = Box<
    dyn FnOnce(Arc<CraftyApp>, tokio::sync::watch::Receiver<bool>) -> tokio::task::JoinHandle<()>
        + Send,
>;

/// Spawn one or more tier-C [`JobConsumer`] loops with a shared stop channel.
#[derive(Default)]
pub struct ConsumerGroup {
    streams: Vec<String>,
    spawners: Vec<ConsumerSpawnFn>,
}

impl ConsumerGroup {
    /// Empty group — chain [`.add`](Self::add) then [`.spawn`](Self::spawn).
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Register a consumer (pass the generated unit struct for type inference).
    #[must_use]
    pub fn add<C: JobConsumer>(mut self, consumer: C, opts: ConsumerOpts) -> Self {
        self.streams.push(C::STREAM.to_string());
        self.spawners.push(Box::new(move |app, stop| {
            app.spawn_consumer(consumer, opts, stop)
        }));
        self
    }

    /// Split into stream names and spawn closures for [`CraftyAppBuilder::consumers`].
    #[must_use]
    pub fn into_parts(self) -> (Vec<String>, Vec<ConsumerSpawnFn>) {
        (self.streams, self.spawners)
    }

    /// Start every registered consumer; returns `(stop_tx, join handles)`.
    pub fn spawn(
        self,
        app: &Arc<CraftyApp>,
    ) -> (
        tokio::sync::watch::Sender<bool>,
        Vec<tokio::task::JoinHandle<()>>,
    ) {
        let (stop_tx, stop_rx) = tokio::sync::watch::channel(false);
        let handles = self
            .spawners
            .into_iter()
            .map(|spawn| spawn(Arc::clone(app), stop_rx.clone()))
            .collect();
        (stop_tx, handles)
    }
}

/// Options for [`CraftyApp::spawn_consumer`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ConsumerOpts {
    /// Worker instance id on this node (distinct consumers on the same stream).
    pub instance: u32,
    /// Maximum jobs leased per poll ([`run_queue_consumer`] batch size).
    pub batch: usize,
    /// Sleep between polls when the queue is empty.
    pub idle_sleep: Duration,
}

impl Default for ConsumerOpts {
    fn default() -> Self {
        Self {
            instance: 0,
            batch: 1,
            idle_sleep: Duration::from_millis(100),
        }
    }
}

/// Handler registered via [`macro@crate::consumer`].
///
/// Implementations are generated by the attribute macro; spawn with
/// [`CraftyApp::spawn_consumer`].
pub trait JobConsumer: Send + Sync + 'static {
    /// Job stream name passed to `#[consumer("…")]`.
    const STREAM: &'static str;

    /// Error returned when the handler rejects a payload (job is nacked).
    type Error: std::fmt::Debug + Send + 'static;

    /// Process one leased job payload.
    fn handle(payload: &[u8]) -> impl Future<Output = Result<(), Self::Error>> + Send;
}

impl CraftyApp {
    /// Spawn a background task that leases from `C::STREAM`, invokes the handler, and ack/nacks.
    ///
    /// Requires the stream to be registered via [`crate::CraftyAppBuilder::queue`].
    /// Pass a [`tokio::sync::watch`] stop receiver to shut the loop down cleanly.
    /// The `_consumer` value is only used for type inference (see [`macro@crate::consumer`]).
    ///
    /// # Panics
    /// If `C::STREAM` was not registered on the cluster.
    pub fn spawn_consumer<C: JobConsumer>(
        self: &Arc<Self>,
        _consumer: C,
        opts: ConsumerOpts,
        stop: tokio::sync::watch::Receiver<bool>,
    ) -> tokio::task::JoinHandle<()> {
        let app = Arc::clone(self);
        tokio::spawn(async move {
            let queue = app
                .cluster()
                .job_queue(C::STREAM)
                .expect("consumer stream must be registered via .queue");
            let worker = WorkerId {
                node: app.cluster().node_id(),
                instance: opts.instance,
            };
            run_queue_consumer(
                queue,
                worker,
                opts.batch,
                opts.idle_sleep,
                stop,
                |payload| {
                    let payload = payload.to_vec();
                    async move { C::handle(&payload).await }
                },
            )
            .await;
        })
    }
}
